version: "3.9"

services:
  backend:
    build:
      context: ./backend
      target: prod
    container_name: backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./vector_store:/app/vector_store
    environment:
      - PYTHONUNBUFFERED=1
      - ENVIRONMENT=production
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      target: prod
    container_name: frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge