version: "3.9"

services:
  backend:
    build:
      context: ./backend
      target: prod
    container_name: backend
    restart: unless-stopped
    user: "0:0"
    ports:
      - "8000:8000"
    volumes:
      - ./vector_store:/app/vector_store
      - ./processed:/app/processed
      - ./uploads:/app/uploads
      - ./.env:/app/.env:ro
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      target: prod
    container_name: frontend
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro    # ADD THIS LINE
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge