import json


def get_dummy_json() -> str:
    data = {
        "resume": {
            "name": "Saugat Timilsina",
            "title": "Full Stack Engineer | Data Analytics and Engineering",
            "experience": "6+ years",
            "location": "Wollongong, NSW, Australia",
            "summary": "Software Engineer with 6+ years of experience as a Senior Mobile and Full Stack Developer, now transitioning into Data Engineering and Machine Learning after completing a master’s in computer science (Big Data & ML). Skilled in Mobile Dev, Python, and SQL, ETL, ELT and Generative AI with expertise across Android, cross-platform apps, databases, and CRM systems.",
            "skills": [
                "Data Analytics",
                "ETL/ELT pipelines",
                "Python",
                "SQL",
                "Java",
                "Kotlin",
                "Dart",
                "JavaScript",
                "Machine Learning",
                "MongoDB",
                "PostgreSQL",
                "AWS",
            ],
            "work_experience": [
                {
                    "company": "PU Assist, Hamro Calendar",
                    "position": "Founder & Developer",
                    "duration": "8 years",
                    "key_responsibilities": [
                        "Built and published cross-platform apps in Flutter with 30K+ daily users.",
                        "Integrated Firebase Realtime DB, Analytics, Crashlytics, and REST APIs for real-time data sync and reporting.",
                        "Managed full app lifecycle: backend integration, CI/CD (GitHub Actions), Dockerised services, and Play/App Store publishing.",
                        "Designed and deployed an automated ETL pipeline using web scraping, APIs, and PDF parsing.",
                    ],
                    "technologies_used": [
                        "Flutter",
                        "Firebase",
                        "REST APIs",
                        "Docker",
                        "GitHub Actions",
                    ],
                },
                {
                    "company": "Virtual Technology PVT LTD",
                    "position": "Mobile App and Full Stack Developer",
                    "duration": "5 years 9 months",
                    "key_responsibilities": [
                        "Managed data extraction and transformation from government APIs into secure databases.",
                        "Designed automated workflows to maintain data consistency and reduce manual reporting errors.",
                        "Partnered with teams to define data sets and prepare reports that supported business intelligence initiatives.",
                        "Contributed to a COVID-19 contact tracing app.",
                    ],
                    "technologies_used": ["APIs", "GIS", "Google Play", "App Store"],
                },
                {
                    "company": "Star Phones PTY LTD",
                    "position": "Hardware / Customer Support",
                    "duration": "Part-time",
                    "key_responsibilities": [
                        "Prepared data and inventory reports, performing validation and reconciliation.",
                        "Provided support for O365, networking, and POS systems.",
                        "Supported internal systems monitoring.",
                    ],
                    "technologies_used": ["O365"],
                },
                {
                    "company": "Pokhara Engineering College",
                    "position": "Part-time Lecturer",
                    "duration": "2 years 8 months",
                    "key_responsibilities": [
                        "Taught Android and Flutter development with backend integration.",
                        "Mentored students on applying SQL, Python, and Firebase.",
                    ],
                    "technologies_used": [
                        "Android",
                        "Flutter",
                        "SQL",
                        "Python",
                        "Firebase",
                    ],
                },
                {
                    "company": "Metashrine Pvt Ltd",
                    "position": "Junior Android Developer",
                    "duration": "1 year 3 months",
                    "key_responsibilities": [
                        "Developed a restaurant menu & booking system with Java and MVC architecture.",
                        "Integrated RESTful APIs for real-time bookings.",
                    ],
                    "technologies_used": ["Java", "MVC"],
                },
            ],
            "projects": [
                {
                    "project_name": "RAG-based AI Chatbot",
                    "description": "Currently developing a portfolio website chatbot that integrates full-stack development, ETL pipelines, vector databases, and LLMs.",
                    "technologies_used": ["ETL", "LLMs"],
                    "role_or_contribution": "Developer",
                },
                {
                    "project_name": "iPaper",
                    "description": "Capstone project focused on automated research paper summarisation and grouping.",
                    "technologies_used": ["RAG", "LLM", "dashboards"],
                    "role_or_contribution": "Developer",
                },
            ],
            "education": [
                {
                    "degree": "Master of Computer Science",
                    "institution": "University of Wollongong, Australia",
                    "year_completed": "2025",
                },
                {
                    "degree": "Bachelor of Computer Engineering",
                    "institution": "Pokhara Engineering College, Nepal",
                    "year_completed": "2018",
                },
            ],
            "certifications": [],
            "achievements": [
                "Winner, Software Engineering Competition; Represented the college at Tech Expo."
            ],
            "soft_skills": [
                "Stakeholder Engagement",
                "Mentoring",
                "Communication",
                "Collaboration",
                "Attention to detail",
            ],
        },
        "job": {
            "title": "Graduate Data Analyst",
            "company": "Abacus Group",
            "location": "",
            "type": "Full-time",
            "postedDate": "",
            "requiredSkills": [
                "Data Analytics",
                "Microsoft Excel",
                "Data Management",
                "Financial Reporting",
                "Data Cleansing",
                "Anaplan",
                "Communication Skills",
                "Collaboration",
                "Problem Solving",
                "Attention to Detail",
                "Agile Environment",
                "Forecasting",
            ],
            "skillRelevance": [5, 5, 4, 5, 4, 3, 4, 4, 4, 3, 3, 4],
            "keyFocusAreas": [
                "Data Integrity",
                "Financial Data Management",
                "Collaboration with Teams",
                "Reporting and Analysis",
                "Data Import Processes",
                "Stakeholder Communication",
                "Business Intelligence",
                "Project Support",
                "Real Estate Sector Development",
            ],
        },
        "analysis": {
            "overallScore": 65,
            "atsScore": 70,
            "skillsMatched": 4,
            "skillsTotal": 12,
            "experience_relevance": {
                "years_required": "not specified",
                "years_candidate_has": 6,
                "relevance_explanation": "Candidate has extensive experience in data analytics and engineering, but lacks direct experience in financial reporting and specific tools like Anaplan.",
            },
            "keywordsFound": 12,
            "keyword_density": {
                "critical_keywords_present": [
                    "Data Analytics",
                    "Communication Skills",
                    "Collaboration",
                    "Attention to Detail",
                ],
                "critical_keywords_missing": [
                    "Microsoft Excel",
                    "Data Management",
                    "Financial Reporting",
                    "Data Cleansing",
                    "Anaplan",
                    "Forecasting",
                ],
            },
            "missingSkills": [
                "Microsoft Excel",
                "Data Management",
                "Financial Reporting",
                "Data Cleansing",
                "Anaplan",
                "Forecasting",
            ],
            "missing_skills_priority": [1, 1, 1, 1, 2, 2],
            "matchedSkills": [
                "Data Analytics",
                "Communication Skills",
                "Collaboration",
                "Attention to Detail",
            ],
            "recommendations": [
                {
                    "type": "critical",
                    "title": "Add Microsoft Excel proficiency",
                    "description": "Include experience or proficiency with Microsoft Excel, as it is a critical requirement for the role.",
                    "impact": "High",
                    "section": "Skills",
                    "original": "",
                    "suggested": "Microsoft Excel proficiency",
                    "action": "add",
                },
                {
                    "type": "critical",
                    "title": "Highlight Data Management experience",
                    "description": "Detail any experience related to data management processes or tools.",
                    "impact": "High",
                    "section": "Experience",
                    "original": "",
                    "suggested": "Experience with data management tools or processes",
                    "action": "add",
                },
                {
                    "type": "high",
                    "title": "Include Financial Reporting experience",
                    "description": "If applicable, add any experience related to financial reporting or analysis.",
                    "impact": "Medium",
                    "section": "Experience",
                    "original": "",
                    "suggested": "Experience in financial reporting",
                    "action": "add",
                },
                {
                    "type": "medium",
                    "title": "Mention Data Cleansing techniques",
                    "description": "Include any relevant experience or techniques used for data cleansing.",
                    "impact": "Medium",
                    "section": "Experience",
                    "original": "",
                    "suggested": "Experience with data cleansing techniques",
                    "action": "add",
                },
            ],
            "strengths": [
                "Strong background in data analytics and engineering",
                "Proficient in Python and SQL",
                "Experience in building and managing ETL pipelines",
                "Good communication and collaboration skills",
            ],
            "redFlags": [
                "Lack of experience with specific tools like Anaplan and Microsoft Excel",
                "No direct experience in financial reporting or forecasting",
            ],
        },
        "charts": {
            "radial": [
                {"name": "Match Score", "value": 65},
                {"name": "ATS Score", "value": 70},
                {"name": "Skills", "value": 75},
                {"name": "Experience", "value": 60},
            ],
            "competency": [
                {"skill": "Technical Skills", "yours": 75, "required": 70},
                {"skill": "Communication", "yours": 80, "required": 70},
                {"skill": "Collaboration", "yours": 80, "required": 70},
                {"skill": "Problem Solving", "yours": 70, "required": 70},
                {"skill": "Attention to Detail", "yours": 80, "required": 70},
            ],
            "matchProgress": [
                {"month": "Current", "score": 65},
                {"month": "With Missing Skills", "score": 71},
                {"month": "With All Suggestions", "score": 75},
            ],
            "keywords": [
                {"section": "Summary", "matched": 4, "missing": 2},
                {"section": "Skills", "matched": 4, "missing": 6},
                {"section": "Experience", "matched": 4, "missing": 2},
                {"section": "Projects", "matched": 0, "missing": 0},
                {"section": "Education", "matched": 0, "missing": 0},
            ],
            "atsCompatibility": [
                {"name": "Passed", "value": 70},
                {"name": "Failed", "value": 30},
            ],
            "skillPriority": [
                {"name": "Critical", "value": 4, "color": "#ef4444"},
                {"name": "Important", "value": 2, "color": "#f97316"},
                {"name": "Nice to Have", "value": 0, "color": "#3b82f6"},
            ],
        },
    }

    return data
